// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "RAYCARD — HR-Skills SARL"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/connexion": {
            "post": {
                "description": "Vérifie email + mot de passe et déclenche la 2FA obligatoire : envoie un code par email et renvoie un ticket à présenter avec ce code sur /auth/connexion/verifier-code. Aucun token de session n'est émis ici.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connexion (étape 1/2)",
                "parameters": [
                    {
                        "description": "Identifiants",
                        "name": "connexion",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ConnexionRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ConnexionResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "identifiants invalides",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/connexion-google": {
            "post": {
                "description": "Vérifie l'ID token Google et émet directement une session (2FA sautée pour ce chemin). Crée le compte automatiquement s'il n'existe pas encore, ou lie ce compte Google à un compte existant de même email (si Google confirme l'email vérifié).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connexion via Google",
                "parameters": [
                    {
                        "description": "ID token Google, téléphone et pays (utilisés seulement à la création)",
                        "name": "connexion",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ConnexionGoogleRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SessionResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide, ou téléphone/pays manquants pour une première connexion",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "id token invalide, ou email non vérifié pour lier un compte existant",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/connexion/verifier-code": {
            "post": {
                "description": "Échange le ticket obtenu à l'étape 1 et le code reçu par email contre une session complète (access + refresh token). 5 tentatives maximum ; au-delà, le ticket est définitivement invalidé.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connexion (étape 2/2) — vérification du code",
                "parameters": [
                    {
                        "description": "Ticket et code reçu par email",
                        "name": "verification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifierCode2FARequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SessionResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "ticket ou code invalide, expiré, ou tentatives épuisées",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/deconnexion": {
            "post": {
                "description": "Révoque le refresh token fourni (déconnexion idempotente : ne renvoie pas d'erreur si déjà invalide)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Déconnexion",
                "parameters": [
                    {
                        "description": "Refresh token à révoquer",
                        "name": "deconnexion",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RafraichirRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/mot-de-passe-oublie": {
            "post": {
                "description": "Envoie un code par email si un compte existe pour cet email. Répond toujours le même succès générique, que le compte existe ou non (évite l'énumération de comptes).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Demande de réinitialisation de mot de passe",
                "parameters": [
                    {
                        "description": "Email du compte",
                        "name": "demande",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DemanderReinitialisationRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/rafraichir": {
            "post": {
                "description": "Échange un refresh token valide contre une nouvelle paire access/refresh token (rotation)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Rafraîchissement de session",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "rafraichir",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RafraichirRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SessionResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "refresh token invalide, expiré ou révoqué",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/reinitialiser-mot-de-passe": {
            "post": {
                "description": "Change le mot de passe si le code est valide et révoque toutes les sessions actives de l'utilisateur",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Réinitialisation du mot de passe",
                "parameters": [
                    {
                        "description": "Code reçu par email et nouveau mot de passe",
                        "name": "reinitialisation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReinitialiserRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "code invalide, expiré ou déjà utilisé",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/backoffice/kyc/dossiers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backoffice-kyc"
                ],
                "summary": "Liste des dossiers KYC en attente",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.DossierKycDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "403": {
                        "description": "réservé aux administrateurs",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/backoffice/kyc/dossiers/{id}/approuver": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fait passer l'utilisateur au Tier 2 et écrit une entrée d'audit",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backoffice-kyc"
                ],
                "summary": "Approuve un dossier KYC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du dossier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "403": {
                        "description": "réservé aux administrateurs",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "404": {
                        "description": "dossier introuvable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "422": {
                        "description": "dossier déjà traité",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/backoffice/kyc/dossiers/{id}/rejeter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "L'utilisateur reste au Tier 1 ; le motif lui est communiqué, il pourra resoumettre",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backoffice-kyc"
                ],
                "summary": "Rejette un dossier KYC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du dossier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Motif du rejet",
                        "name": "rejet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RejeterDossierRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "403": {
                        "description": "réservé aux administrateurs",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "404": {
                        "description": "dossier introuvable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "422": {
                        "description": "dossier déjà traité",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/kyc/demande-tier2": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée un dossier KYC en attente de revue par un administrateur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Demande de passage au Tier 2",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.DossierKycDTO"
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "409": {
                        "description": "une demande est déjà en attente",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "422": {
                        "description": "l'utilisateur n'est pas au Tier 1",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/kyc/inscription": {
            "post": {
                "description": "Crée un utilisateur et son wallet associé (KYC Tier 1 auto-validé selon les règles du pays)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Inscription d'un nouvel utilisateur",
                "parameters": [
                    {
                        "description": "Données d'inscription",
                        "name": "inscription",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InscriptionRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.InscriptionResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide ou données de validation incorrectes",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "409": {
                        "description": "email ou téléphone déjà utilisé",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "422": {
                        "description": "pays non supporté ou données métier invalides",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/dto.ErreurDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ConnexionGoogleRequestDTO": {
            "type": "object",
            "required": [
                "id_token",
                "pays_code",
                "telephone"
            ],
            "properties": {
                "id_token": {
                    "type": "string"
                },
                "pays_code": {
                    "type": "string",
                    "example": "CI"
                },
                "telephone": {
                    "type": "string",
                    "example": "+2250700000000"
                }
            }
        },
        "dto.ConnexionRequestDTO": {
            "type": "object",
            "required": [
                "email",
                "mot_de_passe"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "awa.kone@example.com"
                },
                "mot_de_passe": {
                    "type": "string",
                    "example": "motdepasse123"
                }
            }
        },
        "dto.ConnexionResponseDTO": {
            "type": "object",
            "properties": {
                "expire_dans_sec": {
                    "type": "integer"
                },
                "ticket": {
                    "type": "string"
                }
            }
        },
        "dto.DemanderReinitialisationRequestDTO": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "awa.kone@example.com"
                }
            }
        },
        "dto.DossierKycDTO": {
            "type": "object",
            "properties": {
                "admin_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "motif_rejet": {
                    "type": "string"
                },
                "statut": {
                    "type": "string"
                },
                "tier_demande": {
                    "type": "integer"
                },
                "traite_at": {
                    "type": "string"
                },
                "utilisateur_id": {
                    "type": "string"
                }
            }
        },
        "dto.ErreurDTO": {
            "type": "object",
            "properties": {
                "erreur": {
                    "type": "string",
                    "example": "un compte existe déjà avec cet email"
                }
            }
        },
        "dto.InscriptionRequestDTO": {
            "type": "object",
            "required": [
                "email",
                "mot_de_passe",
                "nom",
                "pays_code",
                "prenom",
                "telephone"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "awa.kone@example.com"
                },
                "mot_de_passe": {
                    "type": "string",
                    "minLength": 8,
                    "example": "motdepasse123"
                },
                "nom": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Koné"
                },
                "pays_code": {
                    "type": "string",
                    "example": "CI"
                },
                "prenom": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Awa"
                },
                "telephone": {
                    "type": "string",
                    "example": "+2250700000000"
                }
            }
        },
        "dto.InscriptionResponseDTO": {
            "type": "object",
            "properties": {
                "utilisateur": {
                    "$ref": "#/definitions/dto.UtilisateurDTO"
                },
                "wallet": {
                    "$ref": "#/definitions/dto.WalletDTO"
                }
            }
        },
        "dto.RafraichirRequestDTO": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.ReinitialiserRequestDTO": {
            "type": "object",
            "required": [
                "nouveau_mot_de_passe",
                "token"
            ],
            "properties": {
                "nouveau_mot_de_passe": {
                    "type": "string",
                    "minLength": 8,
                    "example": "nouveaumotdepasse123"
                },
                "token": {
                    "type": "string",
                    "example": "042951"
                }
            }
        },
        "dto.RejeterDossierRequestDTO": {
            "type": "object",
            "required": [
                "motif"
            ],
            "properties": {
                "motif": {
                    "type": "string",
                    "minLength": 3,
                    "example": "pièce d'identité illisible"
                }
            }
        },
        "dto.SessionResponseDTO": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "access_token_expire_at": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "refresh_token_expire_at": {
                    "type": "string"
                }
            }
        },
        "dto.UtilisateurDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "awa.kone@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "3fa2c1e4-9b5d-4a2e-8c1a-0e2f6a7b8c9d"
                },
                "kyc_statut": {
                    "type": "string",
                    "example": "verifie"
                },
                "kyc_tier": {
                    "type": "integer",
                    "example": 1
                },
                "nom": {
                    "type": "string",
                    "example": "Koné"
                },
                "pays_code": {
                    "type": "string",
                    "example": "CI"
                },
                "prenom": {
                    "type": "string",
                    "example": "Awa"
                },
                "telephone": {
                    "type": "string",
                    "example": "+2250700000000"
                }
            }
        },
        "dto.VerifierCode2FARequestDTO": {
            "type": "object",
            "required": [
                "code",
                "ticket"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "042951"
                },
                "ticket": {
                    "type": "string"
                }
            }
        },
        "dto.WalletDTO": {
            "type": "object",
            "properties": {
                "devise": {
                    "type": "string",
                    "example": "XOF"
                },
                "id": {
                    "type": "string",
                    "example": "7b8c9d0e-1f2a-4b3c-9d4e-5f6a7b8c9d0e"
                },
                "solde_centimes": {
                    "type": "integer",
                    "example": 0
                },
                "statut": {
                    "type": "string",
                    "example": "actif"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "RAYCARD API",
	Description:      "API backend de la plateforme RAYCARD (wallet Mobile Money + cartes Visa virtuelles).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
