// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "RAYCARD — HR-Skills SARL"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/connexion": {
            "post": {
                "description": "Vérifie email + mot de passe et déclenche la 2FA obligatoire : envoie un code par email et renvoie un ticket à présenter avec ce code sur /auth/connexion/verifier-code. Aucun token de session n'est émis ici.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connexion (étape 1/2)",
                "parameters": [
                    {
                        "description": "Identifiants",
                        "name": "connexion",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ConnexionRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.ConnexionResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "identifiants invalides",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/connexion-google": {
            "post": {
                "description": "Vérifie l'ID token Google (crée le compte automatiquement s'il n'existe pas encore, ou lie ce compte Google à un compte existant de même email si Google confirme l'email vérifié), puis déclenche la 2FA obligatoire comme pour /auth/connexion : envoie un code par email et renvoie un ticket à présenter sur /auth/connexion/verifier-code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connexion via Google (étape 1/2)",
                "parameters": [
                    {
                        "description": "ID token Google, téléphone et pays (utilisés seulement à la création)",
                        "name": "connexion",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ConnexionGoogleRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.ConnexionResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide, ou téléphone/pays manquants pour une première connexion",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "id token invalide, ou email non vérifié pour lier un compte existant",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/connexion/verifier-code": {
            "post": {
                "description": "Échange le ticket obtenu à l'étape 1 et le code reçu par email contre une session complète (access + refresh token). 5 tentatives maximum ; au-delà, le ticket est définitivement invalidé et une alerte de sécurité est envoyée. Une connexion réussie déclenche aussi une notification par email.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connexion (étape 2/2) — vérification du code",
                "parameters": [
                    {
                        "description": "Ticket et code reçu par email",
                        "name": "verification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.VerifierCode2FARequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.SessionResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "ticket ou code invalide, expiré, ou tentatives épuisées",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/deconnexion": {
            "post": {
                "description": "Révoque le refresh token fourni (déconnexion idempotente : ne renvoie pas d'erreur si déjà invalide)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Déconnexion",
                "parameters": [
                    {
                        "description": "Refresh token à révoquer",
                        "name": "deconnexion",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RafraichirRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/empreinte/appareils": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Associe la clé publique générée par l'appareil (après déverrouillage biométrique) à l'utilisateur authentifié. L'empreinte elle-même et la clé privée ne quittent jamais l'appareil.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Enregistrement d'un appareil pour la connexion par empreinte",
                "parameters": [
                    {
                        "description": "Clé publique de l'appareil",
                        "name": "appareil",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.EnregistrerAppareilRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.AppareilResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide ou clé publique mal formée",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/empreinte/appareils/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalide définitivement un appareil (perte, vol, ou l'utilisateur ne veut plus l'utiliser).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Révocation d'un appareil enregistré pour l'empreinte",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de l'appareil",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "404": {
                        "description": "appareil introuvable",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/empreinte/challenge": {
            "post": {
                "description": "Émet un nonce à signer avec la clé privée de l'appareil désigné (déverrouillée par empreinte côté client).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Demande d'un challenge pour la connexion par empreinte",
                "parameters": [
                    {
                        "description": "Appareil concerné",
                        "name": "demande",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.DemanderChallengeEmpreinteRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.ChallengeEmpreinteResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "appareil inconnu ou révoqué",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/empreinte/verifier": {
            "post": {
                "description": "Échange un challenge signé par la clé privée de l'appareil contre une session complète. Contrairement aux autres méthodes de connexion, aucun code par email n'est requis : l'appareil et l'empreinte qui l'a déverrouillé constituent déjà deux facteurs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connexion par empreinte digitale",
                "parameters": [
                    {
                        "description": "Challenge signé",
                        "name": "verification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.VerifierEmpreinteRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.SessionResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "challenge invalide, expiré, ou signature incorrecte",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/mot-de-passe-oublie": {
            "post": {
                "description": "Envoie un code par email si un compte existe pour cet email. Répond toujours le même succès générique, que le compte existe ou non (évite l'énumération de comptes).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Demande de réinitialisation de mot de passe",
                "parameters": [
                    {
                        "description": "Email du compte",
                        "name": "demande",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.DemanderReinitialisationRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/profil": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour le nom et le prénom de l'utilisateur authentifié.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Modification du profil",
                "parameters": [
                    {
                        "description": "Nouveau nom et prénom",
                        "name": "profil",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ModifierProfilRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.UtilisateurDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/profil/email": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Envoie un code de confirmation au NOUVEL email. Le changement ne prend effet qu'après confirmation (voir /auth/profil/email/confirmer).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Demande de changement d'email",
                "parameters": [
                    {
                        "description": "Nouvelle adresse email",
                        "name": "demande",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.DemanderChangementEmailRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "409": {
                        "description": "email déjà utilisé",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/profil/email/confirmer": {
            "post": {
                "description": "Applique le changement d'email si le code reçu au nouvel email est valide. Notifie l'ancienne adresse du changement.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Confirmation du changement d'email",
                "parameters": [
                    {
                        "description": "Code reçu au nouvel email",
                        "name": "confirmation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ConfirmerChangementEmailRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.UtilisateurDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "code invalide, expiré ou déjà utilisé",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "409": {
                        "description": "email déjà utilisé",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/profil/mot-de-passe": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Change le mot de passe de l'utilisateur authentifié, après vérification du mot de passe actuel, et révoque toutes les autres sessions actives.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Changement de mot de passe",
                "parameters": [
                    {
                        "description": "Mot de passe actuel et nouveau mot de passe",
                        "name": "motDePasse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ChangerMotDePasseRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "non authentifié, ou mot de passe actuel incorrect",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/profil/photo": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Stocke la nouvelle photo de profil. Formats acceptés : JPEG, PNG.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Modification de la photo de profil",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Nouvelle photo de profil",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.UtilisateurDTO"
                        }
                    },
                    "400": {
                        "description": "fichier manquant ou illisible",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "422": {
                        "description": "format de fichier non supporté",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/rafraichir": {
            "post": {
                "description": "Échange un refresh token valide contre une nouvelle paire access/refresh token (rotation)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Rafraîchissement de session",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "rafraichir",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RafraichirRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.SessionResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "refresh token invalide, expiré ou révoqué",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/auth/reinitialiser-mot-de-passe": {
            "post": {
                "description": "Change le mot de passe si le code est valide et révoque toutes les sessions actives de l'utilisateur",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Réinitialisation du mot de passe",
                "parameters": [
                    {
                        "description": "Code reçu par email et nouveau mot de passe",
                        "name": "reinitialisation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ReinitialiserRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "code invalide, expiré ou déjà utilisé",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/backoffice/kyc/documents/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Renvoie le contenu brut de l'image (jamais seulement le texte OCR) : c'est sur cette image que l'administrateur doit fonder sa décision d'approbation ou de rejet.",
                "produces": [
                    "image/jpeg",
                    "image/png"
                ],
                "tags": [
                    "backoffice-kyc"
                ],
                "summary": "Récupération d'un document d'identité",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du document",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "403": {
                        "description": "réservé aux administrateurs",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "404": {
                        "description": "document introuvable",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/backoffice/kyc/dossiers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backoffice-kyc"
                ],
                "summary": "Liste des dossiers KYC en attente",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/kyc.DossierKycDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "403": {
                        "description": "réservé aux administrateurs",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/backoffice/kyc/dossiers/{id}/approuver": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fait passer l'utilisateur au Tier 2 et écrit une entrée d'audit",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backoffice-kyc"
                ],
                "summary": "Approuve un dossier KYC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du dossier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "403": {
                        "description": "réservé aux administrateurs",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "404": {
                        "description": "dossier introuvable",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "422": {
                        "description": "dossier déjà traité",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/backoffice/kyc/dossiers/{id}/rejeter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "L'utilisateur reste au Tier 1 ; le motif lui est communiqué, il pourra resoumettre",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backoffice-kyc"
                ],
                "summary": "Rejette un dossier KYC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du dossier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Motif du rejet",
                        "name": "rejet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kyc.RejeterDossierRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "corps de requête invalide",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "403": {
                        "description": "réservé aux administrateurs",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "404": {
                        "description": "dossier introuvable",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "422": {
                        "description": "dossier déjà traité",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/backoffice/kyc/utilisateurs/{id}/documents": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Renvoie les documents téléversés et le texte que l'OCR local en a extrait, pour aider à traiter son dossier de passage de palier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backoffice-kyc"
                ],
                "summary": "Liste des documents d'identité d'un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de l'utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/kyc.DocumentKycDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "403": {
                        "description": "réservé aux administrateurs",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/kyc/demande-tier2": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée un dossier KYC en attente de revue par un administrateur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Demande de passage au Tier 2",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/kyc.DossierKycDTO"
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "409": {
                        "description": "une demande est déjà en attente",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "422": {
                        "description": "l'utilisateur n'est pas au Tier 1",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/kyc/documents": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Stocke le document et en extrait le texte par OCR local (Tesseract) — une aide à la saisie pour l'administrateur qui traitera le dossier, jamais une décision automatique. Formats acceptés : JPEG, PNG.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Téléversement d'un document d'identité",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Photo du document (CNI, passeport...)",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/kyc.DocumentKycDTO"
                        }
                    },
                    "400": {
                        "description": "fichier manquant ou illisible",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "401": {
                        "description": "non authentifié",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "422": {
                        "description": "format de document non supporté",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        },
        "/kyc/inscription": {
            "post": {
                "description": "Crée un utilisateur et son wallet associé (KYC Tier 1 auto-validé selon les règles du pays)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Inscription d'un nouvel utilisateur",
                "parameters": [
                    {
                        "description": "Données d'inscription",
                        "name": "inscription",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kyc.InscriptionRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/kyc.InscriptionResponseDTO"
                        }
                    },
                    "400": {
                        "description": "corps de requête invalide ou données de validation incorrectes",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "409": {
                        "description": "email ou téléphone déjà utilisé",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "422": {
                        "description": "pays non supporté ou données métier invalides",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    },
                    "500": {
                        "description": "erreur interne",
                        "schema": {
                            "$ref": "#/definitions/commun.ErreurDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.AppareilResponseDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nom_appareil": {
                    "type": "string"
                }
            }
        },
        "auth.ChallengeEmpreinteResponseDTO": {
            "type": "object",
            "properties": {
                "challenge": {
                    "type": "string"
                },
                "challenge_id": {
                    "type": "string"
                },
                "expire_dans_sec": {
                    "type": "integer"
                }
            }
        },
        "auth.ChangerMotDePasseRequestDTO": {
            "type": "object",
            "required": [
                "mot_de_passe_actuel",
                "nouveau_mot_de_passe"
            ],
            "properties": {
                "mot_de_passe_actuel": {
                    "type": "string",
                    "example": "ancienmotdepasse123"
                },
                "nouveau_mot_de_passe": {
                    "type": "string",
                    "minLength": 8,
                    "example": "nouveaumotdepasse456"
                }
            }
        },
        "auth.ConfirmerChangementEmailRequestDTO": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "042951"
                }
            }
        },
        "auth.ConnexionGoogleRequestDTO": {
            "type": "object",
            "required": [
                "id_token",
                "pays_code",
                "telephone"
            ],
            "properties": {
                "id_token": {
                    "type": "string"
                },
                "pays_code": {
                    "type": "string",
                    "example": "CI"
                },
                "telephone": {
                    "type": "string",
                    "example": "+2250700000000"
                }
            }
        },
        "auth.ConnexionRequestDTO": {
            "type": "object",
            "required": [
                "email",
                "mot_de_passe"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "awa.kone@example.com"
                },
                "mot_de_passe": {
                    "type": "string",
                    "example": "motdepasse123"
                }
            }
        },
        "auth.ConnexionResponseDTO": {
            "type": "object",
            "properties": {
                "expire_dans_sec": {
                    "type": "integer"
                },
                "ticket": {
                    "type": "string"
                }
            }
        },
        "auth.DemanderChallengeEmpreinteRequestDTO": {
            "type": "object",
            "required": [
                "appareil_id"
            ],
            "properties": {
                "appareil_id": {
                    "type": "string"
                }
            }
        },
        "auth.DemanderChangementEmailRequestDTO": {
            "type": "object",
            "required": [
                "nouvel_email"
            ],
            "properties": {
                "nouvel_email": {
                    "type": "string",
                    "example": "nouveau.email@example.com"
                }
            }
        },
        "auth.DemanderReinitialisationRequestDTO": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "awa.kone@example.com"
                }
            }
        },
        "auth.EnregistrerAppareilRequestDTO": {
            "type": "object",
            "required": [
                "cle_publique",
                "nom_appareil"
            ],
            "properties": {
                "cle_publique": {
                    "type": "string",
                    "example": "MCowBQYDK2VwAyEA..."
                },
                "nom_appareil": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "iPhone d'Awa"
                }
            }
        },
        "auth.ModifierProfilRequestDTO": {
            "type": "object",
            "required": [
                "nom",
                "prenom"
            ],
            "properties": {
                "nom": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Koné"
                },
                "prenom": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Awa"
                }
            }
        },
        "auth.RafraichirRequestDTO": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "auth.ReinitialiserRequestDTO": {
            "type": "object",
            "required": [
                "nouveau_mot_de_passe",
                "token"
            ],
            "properties": {
                "nouveau_mot_de_passe": {
                    "type": "string",
                    "minLength": 8,
                    "example": "nouveaumotdepasse123"
                },
                "token": {
                    "type": "string",
                    "example": "042951"
                }
            }
        },
        "auth.SessionResponseDTO": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "access_token_expire_at": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "refresh_token_expire_at": {
                    "type": "string"
                }
            }
        },
        "auth.UtilisateurDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "awa.kone@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "3fa2c1e4-9b5d-4a2e-8c1a-0e2f6a7b8c9d"
                },
                "kyc_statut": {
                    "type": "string",
                    "example": "verifie"
                },
                "kyc_tier": {
                    "type": "integer",
                    "example": 1
                },
                "nom": {
                    "type": "string",
                    "example": "Koné"
                },
                "pays_code": {
                    "type": "string",
                    "example": "CI"
                },
                "photo_profil": {
                    "type": "string"
                },
                "prenom": {
                    "type": "string",
                    "example": "Awa"
                },
                "telephone": {
                    "type": "string",
                    "example": "+2250700000000"
                }
            }
        },
        "auth.VerifierCode2FARequestDTO": {
            "type": "object",
            "required": [
                "code",
                "ticket"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "042951"
                },
                "ticket": {
                    "type": "string"
                }
            }
        },
        "auth.VerifierEmpreinteRequestDTO": {
            "type": "object",
            "required": [
                "challenge_id",
                "signature"
            ],
            "properties": {
                "challenge_id": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "commun.ErreurDTO": {
            "type": "object",
            "properties": {
                "erreur": {
                    "type": "string",
                    "example": "un compte existe déjà avec cet email"
                }
            }
        },
        "kyc.DocumentKycDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nom_fichier": {
                    "type": "string"
                },
                "texte_extrait": {
                    "type": "string"
                }
            }
        },
        "kyc.DossierKycDTO": {
            "type": "object",
            "properties": {
                "admin_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "motif_rejet": {
                    "type": "string"
                },
                "statut": {
                    "type": "string"
                },
                "tier_demande": {
                    "type": "integer"
                },
                "traite_at": {
                    "type": "string"
                },
                "utilisateur_id": {
                    "type": "string"
                }
            }
        },
        "kyc.InscriptionRequestDTO": {
            "type": "object",
            "required": [
                "email",
                "mot_de_passe",
                "nom",
                "pays_code",
                "prenom",
                "telephone"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "awa.kone@example.com"
                },
                "mot_de_passe": {
                    "type": "string",
                    "minLength": 8,
                    "example": "motdepasse123"
                },
                "nom": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Koné"
                },
                "pays_code": {
                    "type": "string",
                    "example": "CI"
                },
                "prenom": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Awa"
                },
                "telephone": {
                    "type": "string",
                    "example": "+2250700000000"
                }
            }
        },
        "kyc.InscriptionResponseDTO": {
            "type": "object",
            "properties": {
                "utilisateur": {
                    "$ref": "#/definitions/kyc.UtilisateurDTO"
                },
                "wallet": {
                    "$ref": "#/definitions/kyc.WalletDTO"
                }
            }
        },
        "kyc.RejeterDossierRequestDTO": {
            "type": "object",
            "required": [
                "motif"
            ],
            "properties": {
                "motif": {
                    "type": "string",
                    "minLength": 3,
                    "example": "pièce d'identité illisible"
                }
            }
        },
        "kyc.UtilisateurDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "awa.kone@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "3fa2c1e4-9b5d-4a2e-8c1a-0e2f6a7b8c9d"
                },
                "kyc_statut": {
                    "type": "string",
                    "example": "verifie"
                },
                "kyc_tier": {
                    "type": "integer",
                    "example": 1
                },
                "nom": {
                    "type": "string",
                    "example": "Koné"
                },
                "pays_code": {
                    "type": "string",
                    "example": "CI"
                },
                "prenom": {
                    "type": "string",
                    "example": "Awa"
                },
                "telephone": {
                    "type": "string",
                    "example": "+2250700000000"
                }
            }
        },
        "kyc.WalletDTO": {
            "type": "object",
            "properties": {
                "devise": {
                    "type": "string",
                    "example": "XOF"
                },
                "id": {
                    "type": "string",
                    "example": "7b8c9d0e-1f2a-4b3c-9d4e-5f6a7b8c9d0e"
                },
                "solde_centimes": {
                    "type": "integer",
                    "example": 0
                },
                "statut": {
                    "type": "string",
                    "example": "actif"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "RAYCARD API",
	Description:      "API backend de la plateforme RAYCARD (wallet Mobile Money + cartes Visa virtuelles).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
